server:
  port: ${USER_SERVICE_PORT:8001}

spring:
  config:
    import: optional:classpath:/common-dev.yml,optional:classpath:/common-uat.yml,optional:classpath:/common-prod.yml,classpath:/common.yml
  application:
    name: user-service
